name: "indigo_dbt"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" from profile.yml dbt uses for this project.
profile: indigo-dbt

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
  zero_address: "'0x0000000000000000000000000000000000000000'"