CREATE STAGE IDENTIFIER('"WAREHOUSE_DB"."PRODUCTION"."S3_EXPORT_STAGE"')
	URL = 's3://indigo-snowflake-staging/offchain/export/' 
	STORAGE_INTEGRATION = KEYSTONE_PARQUET 
	DIRECTORY = ( ENABLE = FALSE )
;